#!/usr/bin/env python3
"""Generate runic_display_data.ts (embedded dictionary) from a runic wordlist TSV.

Input rows:  runes <TAB> count <TAB> latin1/latin2/...   (lines starting with # are skipped)
Only the FIRST (most frequent) Latin form is kept - it is what the suggestion bar shows.

Usage: python3 build_display_data.py [--wordlist ../wordlist.lite.tsv] [--out runic_display_data.ts]
"""
import argparse, json

ap = argparse.ArgumentParser()
ap.add_argument("--wordlist", default="../wordlist.lite.tsv")
ap.add_argument("--out", default="runic_display_data.ts")
a = ap.parse_args()

lines, n = [], 0
with open(a.wordlist, encoding="utf-8") as f:
    for raw in f:
        if raw.startswith("#") or not raw.strip():
            continue
        p = raw.rstrip("\n").split("\t")
        if len(p) < 3 or not p[1].isdigit():
            continue
        lines.append(f"{p[0]}\t{p[1]}\t{p[2].split('/')[0]}")
        n += 1

with open(a.out, "w", encoding="utf-8", newline="\n") as o:
    o.write("// GENERATED by build_display_data.py - do not edit by hand.\n")
    o.write(f"// {n} entries, one per line: runes<TAB>count<TAB>Polish spelling shown on the suggestion bar\n")
    o.write("const RUNIC_DATA: string = " + json.dumps("\n".join(lines), ensure_ascii=False) + ";\n")
print(f"{n} entries -> {a.out} ({len(open(a.out,'rb').read())/1e6:.1f} MB)")
